services:
  meshcentral:
    volumes:
      - meshcentral-data:/opt/meshcentral/meshcentral-data
      - ./config.local.json:/opt/meshcentral/meshcentral-data/config.json
      - ./plugins:/opt/meshcentral/meshcentral-data/plugins
      - meshcentral-files:/opt/meshcentral/meshcentral-files
      - meshcentral-web:/opt/meshcentral/meshcentral-web
      - meshcentral-backups:/opt/meshcentral/meshcentral-backups

  caddy:
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile:ro
      - ./ssl/certs:/etc/caddy/certs:ro
      - caddy-data:/data
      - caddy-config:/config
